const express=require("express");
const checkAuth = require("../../middlewares/checkAuth");
const checkUserType = require("../../middlewares/checkUserType");
const checkRoleAuth = require("../../middlewares/roleAuth");
const { validateUserLogin, validateUserRegister, validateCode } = require("../../middlewares/validator");
const { registerProveedor, registerUsuario, loginProveedor,logoutUsuario,confirmAccount, loginUsuario } = require("./controller");
const router=express.Router();
router.put("/loginProveedor",loginProveedor);
router.put("/loginUsuario",validateUserLogin,loginUsuario);
router.put("/logoutUsuario",checkAuth,checkUserType(["user"]),checkRoleAuth(["basico"]),logoutUsuario);
router.post("/registerProveedor",registerProveedor);
router.post("/registerUsuario",validateUserRegister,registerUsuario);
router.put("/confirmAccount",validateCode,confirmAccount);
module.exports=router;