const mongoose=require("mongoose");
const {ObjectId}=mongoose.Schema;
const proveedorSchema=new mongoose.Schema({
    razSocial:{
        type:String,
        trim:true,
        required:true
    },
    role:{
        type:String,
        trim:true,
        default:"Basico"
    },
    descripcion:{
        type:String,
        trim:true
    },
    pais:{
        type:String,
        trim:true
    },
    web:{
        type:String,
        trim:true
    },
    correo:{
        type:String,
        trim:true,
        required:true
    },
    telefono:{
        type:String,
        trim:true
    },
    password:{
        type:String,
        trim:true,
        required:true
    },
    licitaciones:[
        {
            type:ObjectId,
            ref:"LicitacionModel"
        }
    ],
    estado:{
        type:String,
        trim:true
    }
},{
    versionKey:false,
    timestamps:true
});
module.exports=mongoose.model("ProveedorModel",proveedorSchema);