export * from './deleteParametros.dao'
export * from './getParametros.dao'
export * from './getParametrosName.dao'
export * from './insertMultipleParametros.dao'
export * from './updateMultipleParametros.dao'
export * from './updateParametro.dao'
